### ISSUE TITLE
requirements

### ISSUE THREAD

**Issue by arijitchabri** [Mario263/Harry-Potter-Invisible-Cloak-Using-Python#1]
Hello,
After running the command pip install cv2 for installing the used cv2 module it's raising the error that the module does not exist.

**Comment by Mario263** [comment]
Hi,

May i know which editor you're using?

if pycharm go to preferences if you're using macos orif you're using
windows add the package from there

**Comment by arijitchabri** [comment]
I am using Vscode in windows.
But in pycharm it's showing the same issue.
![image](https://user-images.githubusercontent.com/56748464/133880279-6f01b71d-2a93-4aae-8fa9-2f6c06123452.png)
